const teammap = {
  "Real Madrid": "RMA",
  "Barcelona": "FCB",
  "Barça": "FCB",
  "Atletico Madrid": "ATM",
  "Atleti": "ATM",
  "Athletic Club": "ATH",
  "Athletic": "ATH",
  "Real Sociedad": "RSO",
  "Real Betis": "BET",
  "Villarreal": "VIL",
  "Sevilla": "SEV",
  "Sevilla FC": "SEV",
  "Valencia": "VAL",
  "Getafe": "GET",
  "Osasuna": "OSA",
  "Celta Vigo": "CEL",
  "Celta": "CEL",
  "Alaves": "ALA",
  "Alavés": "ALA",
  "Rayo Vallecano": "RAY",
  "Mallorca": "MLL",
  "RCD Mallorca": "MLL",
  "Elche": "ELC",
  "Levante": "LEV",
  "Real Oviedo": "OVI",
  "Girona": "GIR",
  "Espanyol": "ESP",
  "Arsenal": "ARS",
  "AFC Bournemouth": "BOU",
  "Brentford": "BRE",
  "Brighton & Hove Albion": "BHA",
  "Chelsea": "CHE",
  "Crystal Palace": "CRY",
  "Everton": "EVE",
  "Fulham": "FUL",
  "Ipswich Town": "IPS",
  "Leicester City": "LEI",
  "Liverpool": "LIV",
  "Manchester City": "MCI",
  "Man City": "MCI",
  "Manchester United": "MUN",
  "Man Utd": "MUN",
  "Newcastle United": "NEW",
  "Nottingham Forest": "NFO",
  "Southampton": "SOU",
  "Tottenham Hotspur": "TOT",
  "Tottenham": "TOT",
  "Spurs": "TOT",
  "West Ham United": "WHU",
  "Wolverhampton Wanderers": "WOL",
  "Wolves": "WOL",
  "PSG": "PSG",
  "Paris Saint-Germain": "PSG",
  "Paris SG": "PSG",
  "AJ Auxerre": "AUX",
  "Auxerre": "AUX",
  "Angers SCO": "ANG",
  "Angers": "ANG",
  "Stade Rennais FC": "REN",
  "Rennes": "REN",
  "Stade Rennais": "REN",
  "AS Monaco FC": "MON",
  "Monaco": "MON",
  "AS Monaco": "MON",
  "FC Lorient": "LOR",
  "Lorient": "LOR",
  "FC Metz": "MET",
  "Metz": "MET",
  "FC Nantes": "NAN",
  "Nantes": "NAN",
  "Le Havre AC": "LEH",
  "Le Havre": "LEH",
  "LOSC Lille": "LIL",
  "Lille": "LIL",
  "Lille OSC": "LIL",
  "OGC Nice": "NIC",
  "Nice": "NIC",
  "Olympique Lyon": "LYO",
  "Lyon": "LYO",
  "OL": "LYO",
  "Paris FC": "PFC",
  "RC de Lens": "LEN",
  "Lens": "LEN",
  "RC Lens": "LEN",
  "Stade Brestois 29": "BRS",
  "Brest": "BRS",
  "Stade Brestois": "BRS",
  "RC Strasbourg Alsace": "STR",
  "Strasbourg": "STR",
  "Racing Strasbourg": "STR",
  "Toulouse FC": "TOU",
  "Toulouse": "TOU",
  "Marseille": "OMC",
  "Olympique de Marseille": "OMC",
  "OM": "OMC",
  "Bayern Munich": "BAY",
  "Bayern": "BAY",
  "FC Bayern": "BAY",
  "Borussia Dortmund": "BVB",
  "Dortmund": "BVB",
  "BVB Dortmund": "BVB",
  "Bayer 04 Leverkusen": "LEV",
  "Leverkusen": "LEV",
  "Bayer Leverkusen": "LEV",
  "Eintracht Frankfurt": "SGE",
  "Frankfurt": "SGE",
  "Eintracht": "SGE",
  "RB Leipzig": "RBL",
  "Leipzig": "RBL",
  "FC Köln": "KOE",
  "Köln": "KOE",
  "Cologne": "KOE",
  "Hiedenheim": "HDF",
  "Heidenheim": "HDF",
  "1. FC Heidenheim": "HDF",
  "FC Augsburg": "AUG",
  "Augsburg": "AUG",
  "FC St. Pauli": "STP",
  "St. Pauli": "STP",
  "Hamburger SV": "HSV",
  "Hamburg": "HSV",
  "TSG 1899 Hoffenheim": "HOF",
  "Hoffenheim": "HOF",
  "TSG Hoffenheim": "HOF",
  "SC Freiburg": "FRE",
  "Freiburg": "FRE",
  "VfB Stuttgart": "VFB",
  "Stuttgart": "VFB",
  "VfL Wolfsburg": "WOB",
  "Wolfsburg": "WOB",
  "Union Berlin": "UNB",
  "1. FC Union Berlin": "UNB",
  "1. FSV Mainz 05": "MAI",
  "Mainz": "MAI",
  "Mainz 05": "MAI",
  "Borussia Mgladbach": "BMG",
  "Mönchengladbach": "BMG",
  "Gladbach": "BMG",
  "AC Milan": "ACM",
  "Milan": "ACM",
  "Fiorentina": "FIO",
  "ACF Fiorentina": "FIO",
  "AS Roma": "ROM",
  "Roma": "ROM",
  "Atalanta": "ATA",
  "Atalanta BC": "ATA",
  "Bologna": "BOL",
  "Bologna FC 1909": "BOL",
  "Cagliari": "CAG",
  "Cagliari Calcio": "CAG",
  "Como 1907": "COMO",
  "Como": "COMO",
  "Genoa C.F.C.": "GEN",
  "Genoa": "GEN",
  "Hellas Verona": "VER",
  "Verona": "VER",
  "Inter Milan": "INT",
  "Inter": "INT",
  "Juventus": "JUV",
  "Juventus FC": "JUV",
  "S.S. Lazio": "LAZ",
  "Lazio": "LAZ",
  "SS Lazio": "LAZ",
  "Parma Calcio 1913": "PAR",
  "Parma": "PAR",
  "Pisa SC": "PSA",
  "Pisa": "PSA",
  "U.S. Sassuolo Calcio": "SAS",
  "Sassuolo": "SAS",
  "Napoli": "NAP",
  "SSC Napoli": "NAP",
  "Torino": "TOR",
  "Torino FC": "TOR",
  "Udinese": "UDI",
  "Udinese Calcio": "UDI",
  "Cremonese": "CRE",
  "US Cremonese": "CRE",
  "Lecce": "LEC",
  "US Lecce": "LEC"
};

export default teammap;
