const teammap = {
  "Real Madrid": "RMA",
  "Barcelona": "FCB",
  "Barça": "FCB",
  "Atletico Madrid": "ATM",
  "Atleti": "ATM",
  "Athletic Club": "ATH",
  "Athletic": "ATH",
  "Real Sociedad": "RSO",
  "Real Betis": "BET",
  "Villarreal": "VIL",
  "Sevilla": "SEV",
  "Sevilla FC": "SEV",
  "Valencia": "VAL",
  "Getafe": "GET",
  "Osasuna": "OSA",
  "Celta Vigo": "CEL",
  "Celta": "CEL",
  "Alaves": "ALA",
  "Alavés": "ALA",
  "Rayo Vallecano": "RAY",
  "Mallorca": "MLL",
  "RCD Mallorca": "MLL",
  "Elche": "ELC",
  "Levante": "LEV",
  "Real Oviedo": "OVI",
  "Girona": "GIR",
  "Espanyol": "ESP",
  "Arsenal": "ARS",
  "AFC Bournemouth": "BOU",
  "Brentford": "BRE",
  "Brighton & Hove Albion": "BHA",
  "Chelsea": "CHE",
  "Crystal Palace": "CRY",
  "Everton": "EVE",
  "Fulham": "FUL",
  "Ipswich Town": "IPS",
  "Leicester City": "LEI",
  "Liverpool": "LIV",
  "Manchester City": "MCI",
  "Man City": "MCI",
  "Manchester United": "MUN",
  "Man Utd": "MUN",
  "Newcastle United": "NEW",
  "Nottingham Forest": "NFO",
  "Southampton": "SOU",
  "Tottenham Hotspur": "TOT",
  "Tottenham": "TOT",
  "Spurs": "TOT",
  "West Ham United": "WHU",
  "Wolverhampton Wanderers": "WOL",
  "Wolves": "WOL"
};

export default teammap;
