import juventusLogo from './assets/juventus-logo.png'
import portugalFlag from './assets/portugal-logo.svg'
import franceFlag from './assets/france-logo.svg'
import brazilFlag from './assets/brazil-logo.svg'

const teams = [
  {
    id: 1,
    name: "Real Madrid",
    league: "La Liga",
    country: "Spain",
    crest: "https://crests.football-data.org/86.svg",
    flag: "https://flagcdn.com/es.svg",
    rank: 1,
    points: 95,
    titles: 35,
    instagram: "https://www.instagram.com/realmadrid",
    website: "https://www.realmadrid.com",
  },
  {
    id: 2,
    name: "FC Barcelona",
    league: "La Liga",
    country: "Spain",
    crest: "https://crests.football-data.org/81.svg",
    flag: "https://flagcdn.com/es.svg",
    rank: 2,
    points: 88,
    titles: 27,
    instagram: "https://www.instagram.com/fcbarcelona",
    website: "https://www.fcbarcelona.com",
  },
  {
    id: 3,
    name: "Manchester City",
    league: "Premier League",
    country: "England",
    crest: "https://crests.football-data.org/65.svg",
    flag: "https://flagcdn.com/gb.svg",
    rank: 1,
    points: 90,
    titles: 9,
    instagram: "https://www.instagram.com/mancity",
    website: "https://www.mancity.com",
  },
  {
    id: 4,
    name: "Manchester United",
    league: "Premier League",
    country: "England",
    crest: "https://crests.football-data.org/66.svg",
    flag: "https://flagcdn.com/gb.svg",
    rank: 4,
    points: 75,
    titles: 20,
    instagram: "https://www.instagram.com/manchesterunited",
    website: "https://www.manutd.com",
  },
  {
    id: 5,
    name: "Liverpool",
    league: "Premier League",
    country: "England",
    crest: "https://crests.football-data.org/64.svg",
    flag: "https://flagcdn.com/gb.svg",
    rank: 3,
    points: 78,
    titles: 19,
    instagram: "https://www.instagram.com/liverpoolfc",
    website: "https://www.liverpoolfc.com",
  },
  {
    id: 6,
    name: "Paris Saint-Germain",
    league: "Ligue 1",
    country: "France",
    crest: "https://crests.football-data.org/524.svg",
    flag: "https://flagcdn.com/fr.svg",
    rank: 1,
    points: 85,
    titles: 11,
    instagram: "https://www.instagram.com/psg",
    website: "https://www.psg.fr",
  },
  {
    id: 7,
    name: "Bayern Munich",
    league: "Bundesliga",
    country: "Germany",
    crest: "https://crests.football-data.org/5.svg",
    flag: "https://flagcdn.com/de.svg",
    rank: 1,
    points: 82,
    titles: 33,
    instagram: "https://www.instagram.com/fcbayern",
    website: "https://fcbayern.com",
  },
  {
    id: 8,
    name: "Chelsea",
    league: "Premier League",
    country: "England",
    crest: "https://crests.football-data.org/61.svg",
    flag: "https://flagcdn.com/gb.svg",
    rank: 6,
    points: 65,
    titles: 6,
    instagram: "https://www.instagram.com/chelseafc",
    website: "https://www.chelseafc.com",
  },
  {
    id: 9,
    name: "Brazil",
    league: "International",
    country: "Brazil",
    crest: brazilFlag,
    flag: "https://flagcdn.com/br.svg",
    rank: 3,
    points: 98,
    titles: 5,
    instagram: "https://www.instagram.com/cbf_futebol",
    website: "https://www.cbf.com.br",
  },
  {
    id: 10,
    name: "Argentina",
    league: "International",
    country: "Argentina",
    crest: "https://upload.wikimedia.org/wikipedia/en/c/c1/Argentina_national_football_team_logo.svg",
    flag: "https://flagcdn.com/ar.svg",
    rank: 1,
    points: 100,
    titles: 3,
    instagram: "https://www.instagram.com/afaseleccion",
    website: "https://www.afa.com.ar",
  },
  {
    id: 11,
    name: "Arsenal",
    league: "Premier League",
    country: "England",
    crest: "https://crests.football-data.org/57.svg",
    flag: "https://flagcdn.com/gb.svg",
    rank: 2,
    points: 87,
    titles: 13,
    instagram: "https://www.instagram.com/arsenal",
    website: "https://www.arsenal.com",
  },
  {
    id: 12,
    name: "Atlético Madrid",
    league: "La Liga",
    country: "Spain",
    crest: "https://crests.football-data.org/78.svg",
    flag: "https://flagcdn.com/es.svg",
    rank: 3,
    points: 76,
    titles: 11,
    instagram: "https://www.instagram.com/atleticodemadrid",
    website: "https://en.atleticodemadrid.com",
  },
  {
    id: 13,
    name: "Portugal",
    league: "International",
    country: "Portugal",
    crest: portugalFlag,
    flag: "https://flagcdn.com/pt.svg",
    rank: 6,
    points: 92,
    titles: 1,
    instagram: "https://www.instagram.com/portugal",
    website: "https://www.fpf.pt",
  },
  {
    id: 14,
    name: "France",
    league: "International",
    country: "France",
    crest: franceFlag,
    flag: "https://flagcdn.com/fr.svg",
    rank: 2,
    points: 99,
    titles: 2,
    instagram: "https://www.instagram.com/equipedefrance",
    website: "https://www.fff.fr",
  },
  {
    id: 15,
    name: "Inter Milan",
    league: "Serie A",
    country: "Italy",
    crest: "https://crests.football-data.org/108.svg",
    flag: "https://flagcdn.com/it.svg",
    rank: 1,
    points: 86,
    titles: 20,
    instagram: "https://www.instagram.com/inter",
    website: "https://www.inter.it",
  },
  {
    id: 16,
    name: "AC Milan",
    league: "Serie A",
    country: "Italy",
    crest: "https://crests.football-data.org/98.svg",
    flag: "https://flagcdn.com/it.svg",
    rank: 2,
    points: 79,
    titles: 19,
    instagram: "https://www.instagram.com/acmilan",
    website: "https://www.acmilan.com",
  },
  {
    id: 17,
    name: "Juventus",
    league: "Serie A",
    country: "Italy",
    crest: juventusLogo,
    flag: "https://flagcdn.com/it.svg",
    rank: 4,
    points: 70,
    titles: 36,
    instagram: "https://www.instagram.com/juventus",
    website: "https://www.juventus.com",
  },
  {
    id: 18,
    name: "Borussia Dortmund",
    league: "Bundesliga",
    country: "Germany",
    crest: "https://crests.football-data.org/4.svg",
    flag: "https://flagcdn.com/de.svg",
    rank: 2,
    points: 78,
    titles: 8,
    instagram: "https://www.instagram.com/bvb09",
    website: "https://www.bvb.de",
  },
  {
    id: 19,
    name: "Spain",
    league: "International",
    country: "Spain",
    crest: "https://upload.wikimedia.org/wikipedia/en/c/c1/Argentina_national_football_team_logo.svg",
    flag: "https://flagcdn.com/es.svg",
    rank: 4,
    points: 94,
    titles: 1,
    instagram: "https://www.instagram.com/sefutbol",
    website: "https://www.rfef.es",
  },
  {
    id: 20,
    name: "Germany",
    league: "International",
    country: "Germany",
    crest: "https://upload.wikimedia.org/wikipedia/en/c/c1/Argentina_national_football_team_logo.svg",
    flag: "https://flagcdn.com/de.svg",
    rank: 5,
    points: 93,
    titles: 4,
    instagram: "https://www.instagram.com/dfb_team",
    website: "https://www.dfb.de",
  },
];


  const leagueIdMap = {
    "Premier League": 2021,
    "La Liga": 2014,
    "Serie A": 2019,
    "Bundesliga": 2002,
    "Ligue 1": 2015,
  }

  const updateTeams = teams.map(team => ({
    ...team,
    leagueId : leagueIdMap[team.league] || 2021
  }));
  
  export default updateTeams;
  
  